Builtin test done with POSIX, needs testing when && and || is working
vkuokka/42sh pull request #3
Opened 2021-05-16 19:22 UTC by Biffenx

Should be ok, not norminetted as it needs testing first. testing can be done when && and || are made.

2021-05-17 06:01 UTC, vkuokka commented on src/launcher/builtins/export.c
> +	//g_shell->env = __environ;
Miksi?

2021-05-17 06:02 UTC, vkuokka commented on src/launcher/builtins/export.c
> +	//g_shell->env = __environ;
Miksi?

2021-05-17 06:07 UTC, vkuokka commented on src/launcher/builtins/unset.c
> +	//g_shell->env = __environ;
Miksi?

2021-05-17 06:12 UTC, vkuokka requested changes
Export ja unset builtin funktioissa on kommentoitu komentotulkin globaalin enviromentin päivitys pois. Enviromentin muistiosoite voi muuttua komentotulkin suorituksen aikana ja tämän takia on erittäin tärkeää, että se haetaa uudestaan enviromentin muokkaamisen jälkeen.

2021-05-17 06:18 UTC, Biffenx commented on src/launcher/builtins/export.c
> +	//g_shell->env = __environ;
mac gives error: src/launcher/builtins/unset.c:32:17: error: use of undeclared identifier '__environ' if not commented

2021-05-17 06:19 UTC, Biffenx commented on src/launcher/builtins/unset.c
> +	//g_shell->env = __environ;
mac gives error: src/launcher/builtins/unset.c:32:17: error: use of undeclared identifier '__environ' if not commented

2021-05-17 06:55 UTC, Biffenx commented on src/launcher/builtins/export.c
> +	//g_shell->env = __environ;
mac os compiles correctly if  g_shell->env =__environ is changed to g_shell->env = environ. Doses this work with linux?

http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/baselib---environ.html

2021-05-22 09:41 UTC, vkuokka commented
Nice.

2021-05-22 09:41 UTC, merged